//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CallLog
    {
        public int F_Id { get; set; }
        public Nullable<int> F_HospitalId { get; set; }
        public string F_Name { get; set; }
        public string F_Tel { get; set; }
        public Nullable<System.DateTime> F_Time { get; set; }
    }
}
