//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosPro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_HosData
    {
        public int F_Id { get; set; }
        public string F_Name { get; set; }
        public string F_Sex { get; set; }
        public string F_IdNo { get; set; }
        public string F_TelPhone { get; set; }
        public string F_Insurance { get; set; }
        public Nullable<System.DateTime> F_BirthDay { get; set; }
        public Nullable<int> F_Age { get; set; }
        public string F_Status { get; set; }
        public Nullable<System.DateTime> F_AdmissionTime { get; set; }
        public string F_DeptName { get; set; }
        public string F_Address { get; set; }
        public string F_Diagnosis { get; set; }
        public Nullable<int> F_HospitalId { get; set; }
        public Nullable<int> F_CallNum { get; set; }
        public Nullable<short> F_WeChatFlag { get; set; }
        public string F_Remark { get; set; }
    }
}
